url: https://cherylrodewig.com
title: Cheryl Rodewig

permalink: /:title/
collections:
  posts:
    output: true
    permalink: /blog/:title/

plugins:
  - jekyll-redirect-from

redirect_from:
  json: false

sass:
  sass_dir: css
  style: compressed

defaults:
  -
    scope:
      path:            "assets/*"
    values:
      sitemap:         false
  -
    scope:
      path:            ""
    values:
      layout: default
      title: Marketer and journalist
      image: /assets/img/home-nav/marketing.jpg
